stages:
  fetch_mnist:
    cmd: |
      wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz -O mnist/train-images.gz;
      gunzip -d mnist/train-images.gz;
      wget http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz -O mnist/train-labels.gz;
      gunzip -d mnist/train-labels.gz;
      wget http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz -O mnist/test-images.gz;
      gunzip -d mnist/test-images.gz;
      wget http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz -O mnist/test-labels.gz;
      gunzip -d mnist/test-labels.gz;
    outs:
      - mnist/test-images:
          cache: false
          persist: true
      - mnist/test-labels:
          cache: false
          persist: true
      - mnist/train-images:
          cache: false
          persist: true
      - mnist/train-labels:
          cache: false
          persist: true
  generate:
    cmd: poetry run python moving_multiscalemnist && tar -C dataset -zcvf mnist.tar.gz .
    deps:
      - moving_multiscalemnist/__main__.py
      - moving_multiscalemnist/digit.py
      - moving_multiscalemnist/generate.py
      - moving_multiscalemnist/mnist.py
      - moving_multiscalemnist/sequence.py
      - moving_multiscalemnist/prepare.py
      - poetry.lock
      - pyproject.toml
      - mnist/
    params:
      - moving_multiscalemnist/defaults.py:
          - DATA_DIR
          - FPS
          - IMAGE_SIZE
          - MAX_DIGITS
          - MIN_DIGITS
          - N_FRAMES
          - OSCILLATIONS
          - SEED
          - SIZES
          - TEST_SIZE
          - TRAIN_SIZE
    outs:
      - mnist.tar.gz
